# -*- coding: utf-8 -*-
"""Context Aware Sentiment Analyazer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hN8g_yPfjBb8gThQPbvDRHpmuexCAXaF
"""

# Cell 1: Install Hugging Face ecosystems and text utilities
!pip install -q transformers datasets accelerate evaluate

import pandas as pd

df = pd.read_csv("/content/financial_phrasebank.csv",
                 encoding='ISO-8859-1',
                 header=None,
                 names=['sentiment', 'text'])

# Display the first few rows to confirm it looks correct
df.head()

# Baseline Classifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

texts = df['text'].values
labels = df['sentiment'].values

# Split data
X_train, X_test, y_train, y_test = train_test_split(texts, labels, test_size=0.2, random_state=42)

# Vectorize text using TF-IDF (Term Frequency-Inverse Document Frequency)
vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train a baseline Logistic Regression model
baseline_model = LogisticRegression(max_iter=1000)
baseline_model.fit(X_train_tfidf, y_train)

# Evaluate
preds = baseline_model.predict(X_test_tfidf)
print(classification_report(y_test, preds))

# Tokenization & Transformer Setup
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from datasets import Dataset
import torch

# Map string labels to integers for the model
label_map = {"negative": 0, "neutral": 1, "positive": 2}
df['label'] = df['sentiment'].map(label_map)

# Convert pandas DataFrame to Hugging Face Dataset
hf_dataset = Dataset.from_pandas(df[['text', 'label']])

# Using DistilBERT for faster training
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
    # Note: Using 'text' as the key to match our DataFrame column name
    return tokenizer(examples["text"], padding="max_length", truncation=True)

# Split and tokenize
dataset_dict = hf_dataset.train_test_split(test_size=0.2, seed=42)
tokenized_datasets = dataset_dict.map(tokenize_function, batched=True)

# Correctly load the model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)

from transformers import TrainingArguments, Trainer

# Cell 5: Fine-tuning on GPU
training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch", # Fixed: evaluation_strategy is now eval_strategy
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True # Speeds up training on the T4 GPU
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
)

# Run the training loop
trainer.train()

import numpy as np
from evaluate import load

# Load accuracy metric
metric = load('accuracy')

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# Update the trainer with the metric function and evaluate
trainer.compute_metrics = compute_metrics
eval_results = trainer.evaluate()

print("Final Evaluation Results:")
display(eval_results)

# Install UI dependencies
!pip install -q gradio

# Launch an interactive dashboard inside your Colab notebook
import gradio as gr
from transformers import pipeline

# Build a fast inference pipeline using your fine-tuned model
nlp_pipeline = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, device=0)

# Map labels back to human-readable strings
label_map = {"LABEL_0": "Negative 📉", "LABEL_1": "Neutral ➡️", "LABEL_2": "Positive 📈"}

def analyze_context_sentiment(text):
    prediction = nlp_pipeline(text)[0]
    readable_label = label_map.get(prediction['label'], prediction['label'])
    return f"Prediction: {readable_label} \nConfidence Score: {prediction['score']:.2f}"

# Create a sleek web UI layout
demo = gr.Interface(
    fn=analyze_context_sentiment,
    inputs=gr.Textbox(placeholder="Enter a financial sentence... (e.g., 'Operating profit rose by 12%')"),
    outputs="text",
    title="Domain-Specific Sentiment Analyzer",
    description="An AI model specialized in parsing contextual business and financial sentiment accurately."
)

# Launch directly in your browser tab via a temporary public link
demo.launch(share=True)

